title: Sameer Pandey # your name (or website title) here
logo: "/images/cover_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a fresher data scientist.
  <br><br>
Expertise in R,Python,SQL,Tableau
  <br><br>
  <a href="https://www.linkedin.com/in/sameer-pandey-923023128/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

